export const sampleCars = [
    {
        _id: "fallback_1",
        brand: "Mercedes-Benz",
        model: "S-Class Maybach",
        year: 2024,
        pricePerDay: 25000,
        category: "Luxury",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatingCapacity: 4,
        location: "VISAKHAPATNAM",
        description: "The pinnacle of automotive luxury and technology. Experience ultimate comfort in this flagship executive sedan.",
        images: ["https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=2070"],
        video: "https://www.youtube.com/embed/dip_8cGOSI4",
        owner: { name: "IdleWheels Concierge", email: "support@idlewheels.com" },
        availability: true,
        isApproved: true,
        features: ["Massaging Seats", "OLED Screens", "Air Suspension"]
    },
    {
        _id: "fallback_2",
        brand: "Porsche",
        model: "911 GT3 RS",
        year: 2023,
        pricePerDay: 35000,
        category: "Sports",
        transmission: "Automatic",
        fuelType: "Petrol",
        seatingCapacity: 2,
        location: "GAJUWAKA",
        description: "A street-legal track monster. Razor-sharp handling and a screaming naturally aspirated flat-six engine.",
        images: ["/cars/porsche.png"],
        video: "https://www.youtube.com/embed/zbwQ1NqY6k8",
        owner: { name: "IdleWheels Concierge", email: "support@idlewheels.com" },
        availability: true,
        isApproved: true,
        features: ["Carbon Fiber Aero", "Roll Cage"]
    },
    {
        _id: "fallback_3",
        brand: "Tesla",
        model: "Model S Plaid",
        year: 2024,
        pricePerDay: 18000,
        category: "Electric",
        transmission: "Automatic",
        fuelType: "Electric",
        seatingCapacity: 5,
        location: "NAD",
        description: "Insane acceleration and sustainable luxury. The fastest accelerating production car on earth.",
        images: ["/cars/tesla.png"],
        video: "https://www.youtube.com/embed/5Y2iJitJ4XQ",
        owner: { name: "IdleWheels Concierge", email: "support@idlewheels.com" },
        availability: true,
        isApproved: true,
        features: ["Autopilot", "Yoke Steering"]
    }
];
